apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/jsztuka/integration-service/config/default?ref=f25b28cf123d3521c1fecfa042842983c0a2bd78
  - https://github.com/jsztuka/integration-service/config/snapshotgc?ref=f25b28cf123d3521c1fecfa042842983c0a2bd78
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/jsztuka/integration-service
    newTag: 812-1
configMapGenerator:
  - name: console-url
    literals:
      - CONSOLE_URL=""
namespace: integration-service
patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector
components:
  - ../rh-certs
